# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely need to edit
# after that. For technical reasons, this file is *NOT* reloaded
# automatically when you use 'jekyll serve'. If you change this file,
# please restart the server process.

# Site settings
title: Asim Jalis
description: > # this means to ignore newlines until "baseurl:"
  Clojure for the win
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asimjalis.github.io" # the base hostname & protocol for your site
email: "asimjalis@gmail.com"
# twitter_username: asimjalis
# github_username:  asimjalis
published: true
future: true
# destination: ./_site/blog
permalink: /blog/:year/:month/:day/:title.html

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-redirect-from

